name: builder
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checks
        run: |
          eval "$(nix print-dev-env)"

          ruff check
          ruff format --check
          pyright
          pytest -vv --color=yes --cov=py_air_control_exporter --cov-report=term py_air_control_exporter test
          hatchling build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
